name: flutter_2d_arkit
description: Example for integrating MYTY Avatar into Flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  arkit_plugin: ^1.0.5
  flutter_unity_widget: ^2022.1.0+7
  flutter_bloc: ^8.1.1
  equatable: ^2.0.3
  cached_network_image: ^3.2.3
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
